<a href="https://colab.research.google.com/github/Gauravkumarlokhande/neural_network_scratch/blob/main/Neural_network_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
import numpy as np
import matplotlib.pyplot as plt

code for single neuron in hidden layer

In [ ]:
input=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2
#every neuron has it's own bias
output=np.dot(weights,input)+bias
print(output)

2.3


Coding a single neuron in output layer

In [ ]:
input=[1,2,3,0.5]
weights=[0.2,0.8,-0.5,1]
bias=2
#every neuron has it's own bias
output=np.dot(weights,input)+bias
print(output)

2.8


coding the last output layer

In [ ]:
input=[0,1,2,3]
weight1=[0.2,0.3,0.4,0.8]
weight2=[0.5,0.6,0.8,0.6]
weight3=[0.7,0.9,0.1,0.2]
bias1=2
bias2=3
bias3=2.2
output=[np.dot(input,weight1)+bias1,np.dot(input,weight2)+bias2,np.dot(input,weight3)+bias3]
print(output)

[np.float64(5.5), np.float64(7.0), np.float64(3.9000000000000004)]


In [ ]:
input=[0,1,2,3]

weight=[[0.2,0.3,0.4,0.8],[0.5,0.6,0.8,0.6],[0.7,0.9,0.1,0.2]]
bias=[2,3,5]
output=np.dot(weight,input)+bias
print(output)

[5.5 7.  6.7]


coding for 3 samples at a time

In [ ]:
input= [[0,1,2],
 [3,7,8],
  [6,4,9],
  [6,4,9]
   ]
weight=[[0.2,0.3,0.4,0.9],
 [0.5,0.6,0.8,0.3],
  [0.7,0.9,0.1,0.5]
  ]
bias=[2,9,4]
output=np.dot(weight,input)+bias
print(output)

[[10.7 16.5 18.5]
 [10.4 18.1 19.7]
 [ 8.3 18.4 18. ]]


neural netwrok with custom layers and inputs

In [ ]:
input= [[0,1,2,4],
 [3,7,8,4],
  [6,4,9,4],
  [6,4,9,4]
   ]
class layer_dense:
  def __init__(self,n_features,neurons):
    self.weights=0.10*np.random.randn(n_features,neurons)
    self.bias=np.zeros((1,neurons))
  def forward(self,inputs):
    output=np.dot(inputs,self.weights)+self.bias
    return output


In [ ]:
layer1=layer_dense(4,5).forward(input)

In [ ]:
print(layer1)

[[-0.0411572   0.34895929 -0.12190519  1.18234768  0.01533928]
 [ 0.21054471  0.15155318 -0.64653233  1.47828336  0.22179332]
 [ 0.66494551 -0.19898758 -0.88303181  0.97532796  0.54041425]
 [ 0.66494551 -0.19898758 -0.88303181  0.97532796  0.54041425]]


neural network with loss

In [ ]:
softmax_output=np.array([[0.7,0.1,0.2],[0.1,0.5,0.4],[0.02,0.9,0.08]])
softmax_output

array([[0.7 , 0.1 , 0.2 ],
       [0.1 , 0.5 , 0.4 ],
       [0.02, 0.9 , 0.08]])

In [ ]:
class_targets=[0,1,1]

In [ ]:
print(softmax_output[range(len(softmax_output)),class_targets])

[0.7 0.5 0.9]


In [ ]:
# to calculate logs
print(-np.log(softmax_output[range(len(softmax_output)),class_targets]))

[0.35667494 0.69314718 0.10536052]
